# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: a0994448-md-normal
  namespace: a0994448
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: worker
